package com.mycompany.myapp;


import com.codename1.components.OnOffSwitch;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import static com.codename1.ui.CN.CENTER;
import com.codename1.ui.CheckBox;
import com.codename1.ui.Container;
import com.codename1.ui.FontImage;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.spinner.Picker;
import com.ijaCampi.gui.HomeForm;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        
        new HomeForm().show();
         
//        Form AjouterHebergement =  new Form("Ajouter Hebergement", BoxLayout.y()); 
//
//        Form Reserver = new Form(new FlowLayout(CENTER, CENTER));
//        Reserver.add(new Label("Reserver Hebergement"));
//        Form AfficherHebergement = new Form(BoxLayout.y());
//        Form f3 = new Form(new FlowLayout(CENTER, CENTER));
//        f3.add(new Label("About"));  
//       Form home = new Form("Sidebar Menu");
//       
//        Toolbar tb = home.getToolbar();
//        
//
//        tb.addMaterialCommandToSideMenu("Ajouter Hebergement", FontImage.MATERIAL_WEB, (ActionListener) (ActionEvent evt) -> {
//            AjouterHebergement.show();
//        });
//         
//        tb.addMaterialCommandToSideMenu("Reserver Hebergement", FontImage.MATERIAL_SETTINGS, e -> {
//            Reserver.show();
//        });
//        
//        tb.addMaterialCommandToSideMenu("About", FontImage.MATERIAL_INFO, e -> {
//            f3.show();
//        });       
//        
//       AjouterHebergement.getToolbar().addCommandToLeftBar("Back", null, (ActionListener) (ActionEvent evt) -> {
//            home.showBack();
//        });
//        
//        Reserver.getToolbar().addCommandToLeftBar("Back", null, (ActionListener) (ActionEvent evt) -> {
//            home.showBack();
//        });
//        AfficherHebergement.getToolbar().addCommandToLeftBar("Back", null, (ActionListener) (ActionEvent evt) -> {
//            home.showBack();
//        });
//        f3.getToolbar().addCommandToLeftBar("Back", null, (ActionListener) (ActionEvent evt) -> {
//            home.showBack();
//        });
//        
//        home.add(new Label("Home Page"));
//        home.show();
//        TextField tfNom = new TextField("", "Nom");
//        TextField tfVille = new TextField("", "ville");
//        TextField tfCategorie =  new TextField("","Categorie");
//        TextField tfCapacite =  new TextField("","Capacité");
//        TextField tfPrix =  new TextField("","Prix");
//        TextField tfNameHebergement =  new TextField("","Nom Hebergement");
//        Picker dateDebut =new Picker();
//        Picker dateFin =new Picker();
//        
//         tfCapacite.addDataChangedListener((i, ii) -> {
//    if(isValidInput(tfCapacite.getText())) {
//       tfCapacite.putClientProperty("LastValid", tfCapacite.getText());
//    } else {
//       tfCapacite.stopEditing();
//       tfCapacite.setText((String)tfCapacite.getClientProperty("LastValid"));
//       tfCapacite.startEditingAsync();
//    }
//});
//          tfPrix.addDataChangedListener((i, ii) -> {
//    if(isValidInput(tfPrix.getText())) {
//       tfPrix.putClientProperty("LastValid", tfPrix.getText());
//    } else {
//       tfPrix.stopEditing();
//       tfPrix.setText((String)tfPrix.getClientProperty("LastValid"));
//       tfPrix.startEditingAsync();
//    }
//});
//        Container c = new Container(BoxLayout.x());
//        Label l = new Label("Disponibilitée : ");
//        OnOffSwitch onOff = new OnOffSwitch();    
//        
//        c.add(l);
//        c.add(onOff);  
//       
////        CheckBox chFoot = new CheckBox("Foot");
////        CheckBox chTennis = new CheckBox("Tennis");
////        CheckBox chLecture = new CheckBox("Lecture");
////        CheckBox chNatation = new CheckBox("Natation");
//        
//        Button btnValider = new Button("Valider");    
//        
//        AjouterHebergement.add(tfNom);
//        AjouterHebergement.add(tfVille);
//        AjouterHebergement.add(tfCategorie);
//        AjouterHebergement.add(tfCapacite);
//        AjouterHebergement.add(tfPrix);
//        AjouterHebergement.add(c);
////        AjouterHebergement.add(chFoot);
////        AjouterHebergement.add(chTennis);
////        AjouterHebergement.add(chLecture);
////        AjouterHebergement.add(chNatation);
//        AjouterHebergement.add(btnValider);
//        
//       // AjouterHebergement.show();
//        Reserver.add(dateDebut);
//        Reserver.add(dateFin);
//        Reserver.add(tfNameHebergement);
//        
//        btnValider.addActionListener(new ActionListener() {
//
//          @Override
//          public void actionPerformed(ActionEvent evt) {
//         
//         Label lNom = new Label("Nom : "+ tfNom.getText());
//         Label lPrenom = new Label("Prenom : "+ tfVille.getText());
//         Label lPwd = new Label("Password : "+ tfCategorie.getText());
//         //Label lDate= new Label("Date : "+ date.getDate().toString());
//         
//         Label lGender = new Label("Gender : ");
//          
//         if(onOff.isValue())lGender.setText("Gender : Homme");
//         else lGender.setText("Gender : Femme");
//         Label lHobis = new Label();
//         String ch ="Hobis : ";
////         if(chFoot.isSelected())ch+= " foot,";
////         if(chTennis.isSelected())ch+= " tennis,";
////         if(chLecture.isSelected())ch+= " Lecture,";
////         if(chNatation.isSelected())ch+= " Natation,";
////         lHobis.setText(ch);
////         AfficherHebergement.add(lNom);
////         AfficherHebergement.add(lPrenom);
////         AfficherHebergement.add(lPwd);
////         //f2.add(lDate);
////         AfficherHebergement.add(lGender);
////         AfficherHebergement.add(lHobis);
////         AfficherHebergement.show();
////         
////          }
////      });
////        
////        
//        
//        
//        
//                
      
      
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

    public boolean isValidInput(String input){

    if(input.contains("a") || input.contains("b") || input.contains("c") 
    || input.contains("d") || input.contains("e") || input.contains("f")
    || input.contains("g") || input.contains("h") || input.contains("i")
    || input.contains("j") || input.contains("k") || input.contains("l")
    || input.contains("m") || input.contains("n") || input.contains("o")
    || input.contains("p") || input.contains("q") || input.contains("r")
    || input.contains("s") || input.contains("t") || input.contains("u")
    || input.contains("v") || input.contains("w") || input.contains("x")
    || input.contains("y") || input.contains("z")) {
        return false;
    }
    else {
        return true;
    }
}

}
